---
- name: Welcome to the fourth Batfish Tutorial!
  hosts: all
  gather_facts: no
  roles:
    - batfish.base

  tasks:

  - name: Execute Batfish related tasks in a block that is "delegate_to -> localhost" and "run_once -> true"
    block:

    - include_tasks: batfish_docker_start.yml

    - name: Pause for Batfish docker container to initialize
      pause:
        seconds: 5

    - name: Setup connection to Batfish service
      bf_session:
        host: localhost
        name: local_batfish

    - name: Initialize the example network
      bf_init_snapshot:
        network: example_network
        snapshot: example_snapshot
        snapshot_data: ../networks/example
        overwrite: true

    - name: Validate the behavior of a packet filter (ACL/Firewall rule)
      bf_assert:
        assertions:
          - type: assert_filter_denies
            name: Confirm that the filter drops SSH traffic
            parameters:
              filter_name: 'as2border2["101"]'
              headers:
                applications: 'ssh'
      register: bf_assert

    - name: Display Batfish validation result details
      debug: msg="{{bf_assert}}"

    - include_tasks: batfish_docker_stop.yml

    delegate_to: localhost
    run_once: true